a = int(input("1-sonni kiriting:"))
b = int(input("2-sonni kiriting:"))
c = int(input("3-sonni kiriting:"))
d = (a>0 or (a<0 or b<0 or c<0)) or (b>0 or (a<0 or b<0 or c<0)) or (c>0 or (a<0 or b<0 or c<0))
print(d)